### ISSUE TITLE
Tri 2 Individual Review

### ISSUE THREAD

**Issue by jplip** [jplip/justin2.0#5]
[Blog](https://jplip.github.io/justin2.0//2024/02/26/CPT-Individual.html)
[Video](https://www.veed.io/view/61a3bbd8-904f-480f-930a-24d13b9ad909?panel=share)

**Comment by sharonkodali** [comment]
0.95/1

Everything required in the CPT requirements provided by College Board seem to be implemented into here. The video is very detailed and also references to the code in order to to show what is actually happening. You show good understanding of your code and I like how the feture added to the overall purpose of the project

What can be improved:

For the first two bullet points maybe add an image to give more proof as to how your data is stored and where the lists are located in the code.
A bit more explanation after each image would be great, instead of just pictures, but I am understanding what's happening in the photos.
Overall:
The issue shows great understanding of the code and CPT requirements. Something that should be improved on is the presentation, which is good, but more pictures and description would bring more cohesivity to the overall page. Video seems clear and the pictures shown definitely meet the CPT requirements.
